# render.yaml
services:
  - type: web
    name: thebiolink-lol
    region: oregon
    plan: free
    runtime: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - key: NEXT_PUBLIC_DATABASE_URL
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
      - key: NEXT_PUBLIC_APP_URL
        value: https://thebiolink.lol  # Change to your custom domain or Render URL
      - key: RATE_LIMIT_WINDOW
        value: "900"
      - key: RATE_LIMIT_MAX
        value: "100"
      - key: BAN_THRESHOLD
        value: "5"
      - key: BAN_DURATION
        value: "3600"
      - key: MAINTENANCE_MODE
        value: "false"

  - type: worker
    name: discord-bot
    region: oregon
    plan: free
    runtime: node
    directory: bot
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: DISCORD_BOT_TOKEN
        fromFile: false
      - key: DISCORD_SERVER_ID
      - key: DISCORD_CLIENT_ID
      - key: DISCORD_CLIENT_SECRET
      - key: NEXT_PUBLIC_APP_URL
      - key: EMAIL
      - key: APP_PASSWORD
