# render.yaml
services:
  - type: web
    name: thebiolink-lol
    runtime: node
    buildCommand: "npm install"
    startCommand: "npm run dev"
    envVars:
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - key: NEXT_PUBLIC_DATABASE_URL
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
      - key: NEXT_PUBLIC_APP_URL
      - key: RATE_LIMIT_WINDOW
      - key: RATE_LIMIT_MAX
      - key: BAN_THRESHOLD
      - key: BAN_DURATION
      - key: MAINTENANCE_MODE

  - type: worker
    name: discord-bot
    runtime: node
    buildCommand: "cd bot && npm install"
    startCommand: "node bot/index.js"
    envVars:
      - key: DISCORD_BOT_TOKEN
        fromFile: false
      - key: DISCORD_SERVER_ID
      - key: DISCORD_CLIENT_ID
      - key: DISCORD_CLIENT_SECRET
      - key: NEXT_PUBLIC_APP_URL
      - key: EMAIL
      - key: APP_PASSWORD
