# render.yaml
services:
  # === WEB SERVICE: Next.js App (Frontend + API) ===
  - type: web
    name: thebiolink-lol
    plan: free
    runtime: node
    region: oregon
    buildCommand: |
      # Install root dependencies (Next.js, React, Firebase, etc.)
      npm install

      # Build the Next.js app for production
      npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - key: NEXT_PUBLIC_DATABASE_URL
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
      - key: NEXT_PUBLIC_APP_URL
        value: https://thebiolink-lol.onrender.com  # Change to your custom domain
      - key: RATE_LIMIT_WINDOW
        value: "900"
      - key: RATE_LIMIT_MAX
        value: "100"
      - key: BAN_THRESHOLD
        value: "5"
      - key: BAN_DURATION
        value: "3600"
      - key: MAINTENANCE_MODE
        value: "false"

  # === WORKER SERVICE: Discord Bot ===
  - type: worker
    name: discord-bot
    plan: free
    runtime: node
    region: oregon
    directory: bot  # Ensures we're in /bot directory
    buildCommand: |
      # Move to bot/ and install its dependencies
      cd /opt/render/project/src/bot && npm install
    startCommand: |
      # Start the bot
      node index.js
    envVars:
      - key: DISCORD_BOT_TOKEN
        fromFile: false
      - key: DISCORD_SERVER_ID
      - key: DISCORD_CLIENT_ID
      - key: DISCORD_CLIENT_SECRET
      - key: NEXT_PUBLIC_APP_URL
      - key: EMAIL
      - key: APP_PASSWORD
